"""add_context_parsed_by_to_events

Revision ID: 21e54ac1761a
Revises: c5226a2ce4dc
Create Date: 2026-02-28 18:40:10.046962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21e54ac1761a'
down_revision: Union[str, Sequence[str], None] = 'c5226a2ce4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notes')
    op.drop_column('events', 'ingested_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
